from __future__ import annotations

from d02kspipi_fitcore.context_executor import run_code_block

DESCRIPTION = 'Mixing summary and final outputs'
CODE = '# ============================================================\n# Mixing-fit summary and final outputs\n# ============================================================\n\nprint_section("Build mixing summary table")\n\nmix_rows = []\n\nfor par in ["x_mix", "y_mix", "qp_abs", "qp_phi"]:\n    val, err = get_param_value_error(mixing_result, par)\n\n    if par == "qp_phi":\n        mix_rows.append({\n            "parameter": par,\n            "value": val,\n            "error": err,\n            "value (%) or deg": np.degrees(val),\n            "error (%) or deg": np.degrees(err) if np.isfinite(err) else np.nan,\n            "floating": par in MIXING_FLOAT_PARAMS,\n        })\n    elif par in ["x_mix", "y_mix"]:\n        mix_rows.append({\n            "parameter": par,\n            "value": val,\n            "error": err,\n            "value (%) or deg": 100.0 * val,\n            "error (%) or deg": 100.0 * err if np.isfinite(err) else np.nan,\n            "floating": par in MIXING_FLOAT_PARAMS,\n        })\n    else:\n        mix_rows.append({\n            "parameter": par,\n            "value": val,\n            "error": err,\n            "value (%) or deg": val,\n            "error (%) or deg": err,\n            "floating": par in MIXING_FLOAT_PARAMS,\n        })\n\ndf_mixing_summary = pd.DataFrame(mix_rows)\nprint(df_mixing_summary)\n\nsave_dataframe_all_formats(df_mixing_summary, "mixing_summary")\nrender_table_figure(df_mixing_summary, "table_mixing_summary")\n\nqp_abs_val = get_param_value_error(mixing_result, "qp_abs")[0]\nqp_phi_val = get_param_value_error(mixing_result, "qp_phi")[0]\nqp_complex = qp_abs_val * np.exp(1j * qp_phi_val)\n\nprint(f"q/p = {qp_complex.real:.8f} {qp_complex.imag:+.8f} i")\nprint(f"|q/p| = {qp_abs_val:.8f}")\nprint(f"phi(q/p) = {qp_phi_val:.8f} rad = {np.degrees(qp_phi_val):.6f} deg")\n\nmixing_extra = {\n    "q_over_p_real": float(qp_complex.real),\n    "q_over_p_imag": float(qp_complex.imag),\n    "qp_abs": float(qp_abs_val),\n    "qp_phi_rad": float(qp_phi_val),\n    "qp_phi_deg": float(np.degrees(qp_phi_val)),\n    "nll": extract_result_scalar(mixing_result, ["nll", "fval", "fcn", "fun", "value"]),\n    "edm": extract_result_scalar(mixing_result, ["edm"]),\n    "func_calls": extract_result_scalar(mixing_result, ["func_calls", "nfcn"]),\n    "fit_time_sec": extract_result_scalar(mixing_result, ["time"]),\n}\n\nsave_json(mixing_extra, JSON_DIR / "mixing_extra_summary.json")\n\nwrite_root_output(\n    ROOT_DIR / "fit_results.root",\n    df_components=df_components,\n    df_mixing_summary=df_mixing_summary,\n    dalitz_result=result,\n    mixing_result=mixing_result,\n)\n\nprint_section("Finished")\nprint("Finished at:", _datetime.datetime.now().isoformat(timespec="seconds"))\nprint("Outputs written to:", OUTPUT_DIR)\n\n'

def run(ctx: dict) -> None:
    run_code_block(ctx, CODE, __file__ + "::" + DESCRIPTION)
